#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2025 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


case "$1" in
    configure)
	update-alternatives \
		--install /usr/share/plymouth/themes/default.plymouth default.plymouth \
		/usr/share/plymouth/themes/nitrux-logo/nitrux-logo.plymouth 100

	update-alternatives \
		--set default.plymouth /usr/share/plymouth/themes/nitrux-logo/nitrux-logo.plymouth

	update-alternatives \
		--install /usr/share/plymouth/themes/text.plymouth text.plymouth \
		/usr/share/plymouth/themes/nitrux-text/nitrux-text.plymouth 100

	update-alternatives \
		--install /usr/share/plymouth/themes/bgrt.plymouth bgrt.plymouth \
		/usr/share/plymouth/themes/bgrt/bgrt.plymouth 100
		
	if which update-initramfs >/dev/null 2>&1
	then
	    update-initramfs -u
	fi
	;;

    abort-upgrade|abort-deconfigure|abort-remove)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac


# -- Set Plymouth default properly.

cat <<EOF > /etc/plymouth/plymouthd.conf
# plymouthd.conf
# Configuration file for plymouthd.
# Nitux Latinoamericana S.C. (2025).

[Daemon]
Theme=nitrux-logo
ShowDelay=0
DeviceTimeout=8
EOF
