#!/bin/sh

set -e

if [ "x$1" = xremove ]; then
	update-alternatives \
		--remove default.plymouth /usr/share/plymouth/themes/nitrux-logo/nitrux-logo.plymouth

        update-alternatives \
		--remove text.plymouth /usr/share/plymouth/themes/nitrux-text/nitrux-text.plymouth

fi

#DEBHELPER#
